'use strict';
const root=document.documentElement;
const toggle=document.querySelector('[data-language]');
let language=new URLSearchParams(location.search).get('lang')==='ar'?'ar':'en';
function applyLanguage(){root.lang=language;root.dir=language==='ar'?'rtl':'ltr';if(toggle){toggle.textContent=language==='ar'?'English':'العربية';toggle.lang=language==='ar'?'en':'ar';toggle.setAttribute('aria-label',language==='ar'?'Switch to English':'التبديل إلى العربية');}document.title=root.dataset[language==='ar'?'titleAr':'titleEn']||document.title;for(const link of document.querySelectorAll('a[data-local]')){const u=new URL(link.getAttribute('href'),location.href);if(language==='ar')u.searchParams.set('lang','ar');else u.searchParams.delete('lang');link.href=u.href;}if(window.harisRecord)renderRecord(window.harisRecord);}
toggle?.addEventListener('click',()=>{language=language==='en'?'ar':'en';const u=new URL(location.href);if(language==='ar')u.searchParams.set('lang','ar');else u.searchParams.delete('lang');history.replaceState(null,'',u);applyLanguage();});
document.querySelector('[data-print]')?.addEventListener('click',()=>window.print());
const recordTitles={en:['Prepare the assigned customer’s note','Try another customer’s record','Ask to save the note'],ar:['إعداد مذكرة العميل المصرّح به','محاولة فتح سجل عميل آخر','طلب حفظ المذكرة']};
const explanations={en:['Haris allowed a draft for the assigned customer. A useful answer, produced locally.','Haris denied access before calling the model. The employee was not assigned to this customer.','The draft stopped for independent review. A different person must approve this exact text before filing.'],ar:['سمح حارس بإعداد مسودة للعميل المصرّح به. أُنتجت هذه الإجابة المفيدة محلياً.','رفض حارس الوصول قبل استدعاء النموذج، لأن الموظف غير مكلّف بهذا العميل.','توقفت المسودة للمراجعة المستقلة. يجب أن يوافق شخص آخر على النص نفسه قبل تسجيله.']};
let selected=0;
function renderRecord(d){const ids=['B01-basic','A09-same-tenant-resource','P01-file'];const c=d.live.find(x=>x.id===ids[selected]);if(!c)return;document.querySelector('[data-record-title]').textContent=recordTitles[language][selected];const status=document.querySelector('[data-record-status]');status.textContent=language==='ar'?{allowed:'مسودة مسموحة',blocked:'الوصول محظور',approval_required:'بانتظار موافقة بشرية'}[c.result.status]:{allowed:'Draft allowed',blocked:'Access blocked',approval_required:'Human approval required'}[c.result.status];status.className='status '+c.result.status;document.querySelector('[data-record-explanation]').textContent=explanations[language][selected];document.querySelector('[data-record-output]').textContent=c.result.output;document.querySelector('[data-record-meta]').textContent=language==='ar'?`${c.id} · بيانات اصطناعية · سجل 14 سبتمبر 2026`:`${c.id} · Synthetic data · Recorded 14 September 2026`;document.querySelectorAll('[data-scenario]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));}
if(document.querySelector('[data-record]')){document.querySelectorAll('[data-scenario]').forEach((b,i)=>b.addEventListener('click',()=>{selected=i;if(window.harisRecord)renderRecord(window.harisRecord);}));fetch('evidence/site-data.json').then(r=>{if(!r.ok)throw Error('Evidence unavailable');return r.json();}).then(d=>{window.harisRecord=d;renderRecord(d);}).catch(()=>{document.querySelector('[data-record-meta]').textContent=language==='ar'?'تعذر تحميل السجل الإضافي. النتيجة المعروضة أدناه محفوظة ضمن الصفحة.':'The additional record could not load. The saved result below is included in this page.';});}
applyLanguage();
